# -*- coding: utf-8 -*-
"""ECE214BDementia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SHKAW0YIh2JIj-_sKF7nb_ry3C6DnWKX
"""

from google.colab import drive
drive.mount('/drive')

!pip install transformers datasets torchaudio scikit-learn

import warnings
warnings.filterwarnings("ignore")

SEED = 42

import os
import random
import numpy as np
import torch
from transformers import set_seed

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)
set_seed(SEED)

from collections import defaultdict
from pathlib import Path
import torchaudio
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score, roc_auc_score
from sklearn.preprocessing import StandardScaler

# Commented out IPython magic to ensure Python compatibility.
!unzip -o /drive/MyDrive/S26_ECE_214B_Mini_Project_2.zip -d /content/

PACKAGE_PATH = '/content/S26_ECE_214B_Mini_Project_2'
# %cd {PACKAGE_PATH}

ROOT = Path(".").resolve()
SPLITS_DIR = ROOT / "splits"
SESS_DIR = ROOT / "sessions"
FEATURE_CACHE = ROOT / "features_hubert_base.npz"
MODEL_ID = "facebook/hubert-base-ls960"

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"device = {device}")

def load_two_col(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    for line in path.read_text().splitlines():
        if not line.strip():
            continue
        k, v = line.split("\t", 1)
        out[k] = v
    return out

def load_split(split: str):
    d = SPLITS_DIR / split
    scp = load_two_col(d / "wav.scp")
    text = load_two_col(d / "text")
    lab = {k: int(v) for k, v in load_two_col(d / "utt2label").items()}
    sess = load_two_col(d / "utt2session")
    utts = sorted(scp)
    return {
        "utts": utts,
        "wav": [str(ROOT / scp[u]) for u in utts],
        "text": [text[u] for u in utts],
        "y": [lab[u] for u in utts],
        "sess": [sess[u] for u in utts],
    }

splits = {s: load_split(s) for s in ("train", "dev", "test")}
for s, d in splits.items():
    print(f"{s:5s}: {len(d['utts']):>5d} segments "
          f"({sum(1 for y in d['y'] if y == 0)} Control / "
          f"{sum(1 for y in d['y'] if y == 1)} AD)")

C_GRID = (0.01, 0.1, 0.5, 1.0, 2.0, 4.0, 10.0)

def aggregate_sessions(utts, probs, y, sessions):
    bucket_prob = defaultdict(list)
    bucket_y = {}
    for p, lab, s in zip(probs, y, sessions):
        bucket_prob[s].append(float(p))
        bucket_y[s] = int(lab)
    sids = sorted(bucket_prob)
    sp = np.array([np.mean(bucket_prob[s]) for s in sids])
    sy = np.array([bucket_y[s] for s in sids])
    return sp, sy, sids


def score(y_true, y_prob):
    y_pred = (y_prob >= 0.5).astype(int)
    return {
        "accuracy": float(accuracy_score(y_true, y_pred)),
        "macro_f1": float(f1_score(y_true, y_pred, average="macro")),
        "auroc": float(roc_auc_score(y_true, y_prob)) if len(set(y_true)) == 2 else float("nan"),
        "confusion": confusion_matrix(y_true, y_pred).tolist(),
        "n": int(len(y_true)),
    }


def sweep_logreg(Xtr, ytr, Xdv, dv_u, ydv, sr_dv):
    best = None
    for C in C_GRID:
        clf = LogisticRegression(C=C, max_iter=2000, class_weight="balanced")
        clf.fit(Xtr, ytr)
        dv_prob = clf.predict_proba(Xdv)[:, 1]
        sp, sy, _ = aggregate_sessions(dv_u, dv_prob, ydv, sr_dv)
        m = score(sy, sp)
        print(f"  C={C:<5g}  dev session AUROC={m['auroc']:.3f}  F1={m['macro_f1']:.3f}")
        if best is None or m["auroc"] > best[1]:
            best = (C, m["auroc"], clf)
    print(f"  -> best C = {best[0]}")
    return best[2], best[0]


def report(clf, Xtr, ytr, sr_tr, tr_u,
           Xdv, ydv, sr_dv, dv_u,
           Xte, yte, sr_te, te_u):
    results = {}
    for name, X, y, sess, u in (("train", Xtr, ytr, sr_tr, tr_u),
                                ("dev",   Xdv, ydv, sr_dv, dv_u),
                                ("test",  Xte, yte, sr_te, te_u)):
        prob = clf.predict_proba(X)[:, 1]
        seg = score(np.array(y), prob)
        sp, sy, _ = aggregate_sessions(u, prob, y, sess)
        ses = score(sy, sp)
        results[name] = {"segment": seg, "session": ses}
    print(f"{'split':<6} {'seg acc':>8} {'seg F1':>7} {'seg AUROC':>10} "
          f"{'sess acc':>9} {'sess F1':>8} {'sess AUROC':>11}")
    for name in ("train", "dev", "test"):
        r = results[name]
        print(f"{name:<6} {r['segment']['accuracy']:>8.3f} {r['segment']['macro_f1']:>7.3f} "
              f"{r['segment']['auroc']:>10.3f} {r['session']['accuracy']:>9.3f} "
              f"{r['session']['macro_f1']:>8.3f} {r['session']['auroc']:>11.3f}")
    print("Test session confusion [[TN, FP], [FN, TP]]:")
    print(np.array(results["test"]["session"]["confusion"]))
    return results

from transformers import AutoTokenizer, AutoModel
import torch
import numpy as np
from pathlib import Path
from tqdm.auto import tqdm
from sklearn.preprocessing import StandardScaler

device = "cuda" if torch.cuda.is_available() else "cpu"
print("device =", device)

def extract_text_transformer_features(
    texts,
    utts,
    model_id="bert-base-uncased",
    cache_path=None,
    batch_size=16,
    max_length=128,
    pooling="cls"
):
    """
    Extract text embeddings from BERT/RoBERTa.

    texts: list of transcript strings
    utts: list of utterance IDs
    model_id: Hugging Face model name
    pooling:
        "cls"  = use [CLS] token embedding
        "mean" = mean-pool over all tokens
    """

    if cache_path is not None:
        cache_path = Path(cache_path)
        if cache_path.exists():
            print(f"Loading cached features from {cache_path}")
            z = np.load(cache_path)
            return {k: z[k] for k in z.files}

    tokenizer = AutoTokenizer.from_pretrained(model_id)
    model = AutoModel.from_pretrained(model_id).to(device)
    model.eval()

    features = {}

    for i in tqdm(range(0, len(texts), batch_size), desc=f"Extracting {model_id}"):
        batch_texts = texts[i:i + batch_size]
        batch_utts = utts[i:i + batch_size]

        inputs = tokenizer(
            batch_texts,
            padding=True,
            truncation=True,
            max_length=max_length,
            return_tensors="pt"
        )

        inputs = {k: v.to(device) for k, v in inputs.items()}

        with torch.no_grad():
            outputs = model(**inputs)

        hidden = outputs.last_hidden_state  # [batch, tokens, hidden_dim]

        if pooling == "cls":
            emb = hidden[:, 0, :]  # [CLS] token
        elif pooling == "mean":
            mask = inputs["attention_mask"].unsqueeze(-1)
            emb = (hidden * mask).sum(dim=1) / mask.sum(dim=1)
        else:
            raise ValueError("pooling must be 'cls' or 'mean'")

        emb = emb.cpu().numpy().astype(np.float32)

        for utt, vec in zip(batch_utts, emb):
            features[utt] = vec

    if cache_path is not None:
        np.savez(cache_path, **features)
        print(f"Saved {len(features)} features to {cache_path}")

    return features

all_utts = []
all_texts = []

for split in ("train", "dev", "test"):
    all_utts.extend(splits[split]["utts"])
    all_texts.extend(splits[split]["text"])

bert_feats = extract_text_transformer_features(
    texts=all_texts,
    utts=all_utts,
    model_id="bert-base-uncased",
    cache_path=ROOT / "features_bert_base_uncased_cls.npz",
    batch_size=16,
    max_length=128,
    pooling="cls"
)

def stack_text_transformer(split):
    d = splits[split]
    X = np.stack([bert_feats[u] for u in d["utts"]]).astype(np.float32)
    y = np.array(d["y"], dtype=np.int64)
    sess = d["sess"]
    utts = d["utts"]
    return utts, X, y, sess


tr_u, Xtr_bert, ytr, sr_tr = stack_text_transformer("train")
dv_u, Xdv_bert, ydv, sr_dv = stack_text_transformer("dev")
te_u, Xte_bert, yte, sr_te = stack_text_transformer("test")

print("BERT feature shape:")
print("train:", Xtr_bert.shape)
print("dev:  ", Xdv_bert.shape)
print("test: ", Xte_bert.shape)

scaler_bert = StandardScaler().fit(Xtr_bert)

Xtr_bert_s = scaler_bert.transform(Xtr_bert)
Xdv_bert_s = scaler_bert.transform(Xdv_bert)
Xte_bert_s = scaler_bert.transform(Xte_bert)

print("Sweeping C on dev session AUROC:")
clf_bert, best_C_bert = sweep_logreg(
    Xtr_bert_s, ytr,
    Xdv_bert_s, dv_u, ydv, sr_dv
)

print("\n=== Linguistic baseline: BERT-base CLS + LogReg ===")
results_bert = report(
    clf_bert,
    Xtr_bert_s, ytr, sr_tr, tr_u,
    Xdv_bert_s, ydv, sr_dv, dv_u,
    Xte_bert_s, yte, sr_te, te_u,
)

roberta_feats = extract_text_transformer_features(
    texts=all_texts,
    utts=all_utts,
    model_id="roberta-base",
    cache_path=ROOT / "features_roberta_base_cls.npz",
    batch_size=16,
    max_length=128,
    pooling="cls"
)

def stack_roberta(split):
    d = splits[split]
    X = np.stack([roberta_feats[u] for u in d["utts"]]).astype(np.float32)
    y = np.array(d["y"], dtype=np.int64)
    sess = d["sess"]
    utts = d["utts"]
    return utts, X, y, sess


tr_u, Xtr_rob, ytr, sr_tr = stack_roberta("train")
dv_u, Xdv_rob, ydv, sr_dv = stack_roberta("dev")
te_u, Xte_rob, yte, sr_te = stack_roberta("test")

scaler_rob = StandardScaler().fit(Xtr_rob)

Xtr_rob_s = scaler_rob.transform(Xtr_rob)
Xdv_rob_s = scaler_rob.transform(Xdv_rob)
Xte_rob_s = scaler_rob.transform(Xte_rob)

print("Sweeping C on dev session AUROC:")
clf_roberta, best_C_roberta = sweep_logreg(
    Xtr_rob_s, ytr,
    Xdv_rob_s, dv_u, ydv, sr_dv
)

print("\n=== Linguistic baseline: RoBERTa-base CLS + LogReg ===")
results_roberta = report(
    clf_roberta,
    Xtr_rob_s, ytr, sr_tr, tr_u,
    Xdv_rob_s, ydv, sr_dv, dv_u,
    Xte_rob_s, yte, sr_te, te_u,
)

def get_session_probs(clf, X, y, sess, utts):
    seg_prob = clf.predict_proba(X)[:, 1]
    sess_prob, sess_y, sess_ids = aggregate_sessions(utts, seg_prob, y, sess)

    return pd.DataFrame({
        "session": sess_ids,
        "y_true": sess_y,
        "prob_AD": sess_prob
    })

text_dev = get_session_probs(clf_roberta, Xdv_rob_s, ydv, sr_dv, dv_u)
text_test = get_session_probs(clf_roberta, Xte_rob_s, yte, sr_te, te_u)

def ensure_session_df(model_name, session_output):
    """
    If session_output is already a DataFrame, return it.
    If it is a tuple/list from get_session_probs, convert it to a DataFrame.
    """

    if isinstance(session_output, pd.DataFrame):
        df = session_output.copy()

        # Make sure required columns exist
        required_cols = ["session", "y_true", "prob_AD"]
        missing = [c for c in required_cols if c not in df.columns]

        if missing:
            raise ValueError(
                f"DataFrame is missing required columns: {missing}. "
                f"Available columns are: {list(df.columns)}"
            )

        df["model"] = model_name

        if "y_pred" not in df.columns:
            df["y_pred"] = (df["prob_AD"] >= 0.5).astype(int)

        return df

    else:
        return session_probs_to_df(model_name, session_output)


text_dev_df = ensure_session_df("RoBERTa text", text_dev)
text_test_df = ensure_session_df("RoBERTa text", text_test)

display(text_dev_df.head())
display(text_test_df.head())

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, confusion_matrix

!pip -q install sentence-transformers

from sentence_transformers import SentenceTransformer

cookie_phrases = [
    "a mother washing dishes",
    "a woman standing at the sink",
    "a woman drying a plate",
    "a woman holding a dish towel",
    "a woman looking away from the sink",
    "a woman distracted while doing dishes",
    "a woman standing in a puddle",
    "a woman not noticing the water",
    "a mother unaware of what the children are doing",
    "a mother wearing an apron",
    "a mother in the kitchen",
    "a woman near an overflowing sink",
    "a woman facing forward",
    "a woman holding a plate",
    "a woman doing housework",
    "a woman ignoring the spill",
    "a woman focused on drying dishes",
    "a woman standing by the counter",
    "a woman beside the sink",
    "a woman in front of the window",
    "a boy reaching for cookies",
    "a boy standing on a stool",
    "a boy climbing to reach the cabinet",
    "a boy reaching into a cookie jar",
    "a boy taking cookies from the jar",
    "a boy stealing cookies",
    "a boy grabbing a cookie",
    "a boy balancing on a stool",
    "a boy standing dangerously",
    "a boy about to fall",
    "a boy leaning forward",
    "a boy stretching his arm upward",
    "a boy wearing shorts",
    "a boy with one foot on the stool",
    "a boy holding a cookie",
    "a boy reaching into an open cabinet",
    "a boy looking at the cookie jar",
    "a boy standing too high",
    "a boy in an unsafe position",
    "a child reaching for snacks",
    "a girl asking for a cookie",
    "a girl reaching up",
    "a girl standing below the boy",
    "a girl holding out her hand",
    "a girl waiting for cookies",
    "a girl looking up at the boy",
    "a girl eating a cookie",
    "a girl with her hand near her mouth",
    "a girl standing in the kitchen",
    "a girl reaching toward her brother",
    "a girl wanting a cookie",
    "a girl watching the boy",
    "a girl standing near the stool",
    "a girl pointing upward",
    "a girl participating in taking cookies",
    "a girl standing on the floor",
    "a child asking for food",
    "a child reaching for a snack",
    "a child watching another child climb",
    "a child near the counter",
    "the stool is tipping",
    "the stool is unstable",
    "the stool is leaning",
    "the stool is about to fall",
    "the boy may fall off the stool",
    "the child is in danger",
    "the stool has two legs off balance",
    "the boy is losing balance",
    "the boy is standing on a wobbly stool",
    "the boy is climbing unsafely",
    "the boy is reaching too far",
    "the boy is putting himself at risk",
    "the stool is not steady",
    "a dangerous kitchen situation",
    "a child may get hurt",
    "an unsafe act in the kitchen",
    "the children are unsupervised",
    "the children are doing something risky",
    "the boy is too high up",
    "the child is balancing dangerously",
    "the sink is overflowing",
    "water is spilling from the sink",
    "the faucet is running",
    "the water is pouring over the counter",
    "water is falling onto the floor",
    "the sink is full of water",
    "the kitchen is flooding",
    "the water is running too much",
    "the mother forgot to turn off the faucet",
    "water is overflowing onto the floor",
    "water is splashing down",
    "water is collecting on the floor",
    "a puddle is forming",
    "there is a spill on the floor",
    "the floor is wet",
    "the counter is wet",
    "the sink is too full",
    "the dishes are in the sink",
    "the water is not being noticed",
    "the faucet was left on",
    "the kitchen counter is messy",
    "dishes are on the counter",
    "a plate is on the counter",
    "a cup is on the counter",
    "a bowl is on the counter",
    "there are dishes near the sink",
    "the counter has household items",
    "the kitchen has cabinets",
    "the cabinet door is open",
    "the cookie cabinet is open",
    "the cookie jar is on a shelf",
    "the cookies are stored high up",
    "the children are reaching into a cabinet",
    "the cabinet contains snacks",
    "the kitchen has a sink",
    "the kitchen has a window",
    "the window is above the sink",
    "there are curtains by the window",
    "the curtains are open",
    "there are objects outside the window",
    "a cookie jar is open",
    "cookies are falling out",
    "cookies are being taken",
    "the boy is taking cookies without permission",
    "the girl wants some cookies",
    "the children are sneaking cookies",
    "the children are taking snacks",
    "the children are misbehaving",
    "the children are focused on the cookies",
    "the cookie jar is high in the cabinet",
    "the cookie jar says cookie jar",
    "the boy has opened the cookie jar",
    "the children are sharing cookies",
    "a child is reaching for sweets",
    "a snack is being stolen",
    "the cookie jar is near the edge",
    "the boy is grabbing from the jar",
    "the girl is waiting below",
    "the children are not being watched",
    "the mother is unaware of the cookie theft",
    "a busy kitchen scene",
    "a chaotic kitchen scene",
    "a family kitchen scene",
    "a household scene",
    "a domestic scene",
    "a black-and-white line drawing",
    "a cartoon-style kitchen",
    "a drawing of a kitchen accident",
    "a picture showing multiple problems",
    "a scene with several things going wrong",
    "a kitchen with children and a mother",
    "a mother and two children in the kitchen",
    "children causing trouble in the kitchen",
    "a mother doing chores while children sneak cookies",
    "a sink overflowing while children climb",
    "a dangerous scene with water and a stool",
    "a child safety hazard",
    "an accident waiting to happen",
    "an image showing inattention",
    "a scene of distraction",
    "the mother is multitasking",
    "the mother is distracted by the dishes",
    "the mother is not watching the children",
    "the mother does not see the boy climbing",
    "the mother does not see the water spilling",
    "the mother does not notice the open cabinet",
    "the mother may be unaware of the danger",
    "the mother is holding a dish",
    "the mother is standing in front of the sink",
    "the mother is turned away from the children",
    "the mother’s attention is divided",
    "the mother is focused on chores",
    "the mother is not reacting",
    "the mother is calmly drying dishes",
    "the mother is near the overflowing sink",
    "the boy is on the right side of the children’s area",
    "the girl is standing to the left of the stool",
    "the mother is on the right side of the image",
    "the sink is on the right side",
    "the cabinet is on the left side",
    "the cookie jar is in the upper cabinet",
    "the window is behind the mother",
    "the stool is under the boy",
    "the water is falling in the center-right",
    "the puddle is near the woman’s feet",
    "the dishes are near the sink",
    "the curtains frame the window",
    "the counter runs across the image",
    "the open cabinet is above the children",
    "the children are on the left side",
    "the woman is between the children and the sink",
    "a child reaching up while another waits",
    "a boy passing cookies to a girl",
    "a girl asking her brother for a cookie",
    "a child taking food from a cabinet",
    "a child standing on furniture",
    "children getting cookies without asking",
    "a mother doing dishes while water spills",
    "an overflowing sink in the background",
    "a tipped stool under a climbing child",
    "a kitchen accident happening",
    "a mother unaware of two hazards",
    "a boy in danger of falling",
    "a girl watching the boy climb",
    "water spilling unnoticed",
    "a cookie theft happening during dishwashing",
    "a household accident scene",
    "a child safety problem",
    "an overflowing sink hazard",
    "a slipping hazard on the floor",
    "a fall hazard from the stool",
    "an open cabinet hazard",
    "The boy is stealing cookies.",
    "The girl is asking for a cookie.",
    "The mother is washing dishes.",
    "The sink is overflowing.",
    "The faucet is still on.",
    "The stool is tipping over.",
    "The boy might fall.",
    "The mother does not notice the water.",
    "The children are sneaking snacks.",
    "The floor is getting wet.",
    "The cabinet door is open.",
    "The cookie jar is on the shelf.",
    "The water is spilling onto the floor.",
    "The mother is drying a dish.",
    "The girl is reaching up.",
    "The boy is standing on a stool.",
    "The kitchen is becoming messy.",
    "There is a puddle under the woman.",
    "The children are not being supervised.",
    "Several accidents are happening at once.",
    "boy on stool",
    "girl reaching",
    "mother at sink",
    "overflowing water",
    "open cabinet",
    "cookie jar",
    "tipping stool",
    "wet floor",
    "running faucet",
    "dishes on counter",
    "kitchen sink",
    "window curtains",
    "plate in hand",
    "dish towel",
    "spilled water",
    "children stealing cookies",
    "unsafe climbing",
    "distracted mother",
    "household chores",
    "kitchen accident",
    "a mother rinsing dishes at the sink",
    "a woman rinsing a plate",
    "a mother wiping a dish dry",
    "a woman drying dishes with a towel",
    "a woman holding a plate and towel",
    "a mother standing beside overflowing water",
    "a woman standing near spilled water",
    "a mother with her back partly turned",
    "a woman looking away from the children",
    "a mother distracted by housework",
    "a woman unaware of the cabinet",
    "a mother unaware of the climbing boy",
    "a woman unaware of the tipping stool",
    "a mother unaware of the wet floor",
    "a woman not reacting to the spill",
    "a mother not reacting to the children",
    "a woman facing the viewer",
    "a woman standing near the counter edge",
    "a mother standing near the sink basin",
    "a woman standing in front of a window",
    "a woman beside a running faucet",
    "a mother doing chores in the kitchen",
    "a woman cleaning up dishes",
    "a mother focused on a plate",
    "a woman holding a dishcloth",
    "a woman in an apron near the sink",
    "a woman near a puddle of water",
    "a mother in a busy kitchen",
    "a woman distracted from danger",
    "a mother missing the accident",
    "a boy reaching toward the shelf",
    "a boy stretching for the cookie jar",
    "a boy standing on tiptoe on a stool",
    "a boy leaning over while reaching",
    "a boy losing his balance",
    "a boy slipping from the stool",
    "a boy almost falling backward",
    "a boy almost falling sideways",
    "a boy grabbing cookies from above",
    "a boy taking cookies from a high shelf",
    "a boy reaching into the upper cabinet",
    "a boy balancing on one foot",
    "a boy standing on an unstable stool",
    "a boy putting weight on a tilted stool",
    "a boy reaching while the stool tips",
    "a boy holding the cookie jar lid",
    "a boy with cookies in his hand",
    "a boy passing a cookie down",
    "a boy handing cookies to the girl",
    "a boy sharing stolen cookies",
    "a boy sneaking food from the cabinet",
    "a boy trying not to get caught",
    "a boy climbing in the kitchen",
    "a boy using furniture as a ladder",
    "a boy standing too close to the counter",
    "a boy reaching over the girl",
    "a boy focused on the cookie jar",
    "a boy ignoring the danger",
    "a boy about to tumble",
    "a child climbing near a counter",
    "a child climbing to reach food",
    "a child balancing above the floor",
    "a girl reaching with one hand",
    "a girl holding her hand out",
    "a girl waiting for the boy",
    "a girl expecting a cookie",
    "a girl looking toward the cookie jar",
    "a girl standing near the stool legs",
    "a girl standing close to danger",
    "a girl near the falling stool",
    "a girl watching the cookie theft",
    "a girl participating in sneaking cookies",
    "a girl asking her brother for snacks",
    "a girl looking at her brother",
    "a girl with a cookie near her mouth",
    "a girl eating while standing",
    "a girl standing under the cabinet",
    "a girl reaching toward the boy",
    "a girl waiting below the shelf",
    "a girl standing beside the counter",
    "a girl distracted by cookies",
    "a girl not noticing the water",
    "a girl not noticing the stool tipping",
    "a girl near an unsafe situation",
    "a child watching cookies being taken",
    "a child receiving cookies from another child",
    "a child helping with the cookie theft",
    "a child standing beneath the open cabinet",
    "the children are stealing from the cabinet",
    "the children are trying to get cookies",
    "the children are sharing stolen snacks",
    "the children are acting without permission",
    "the children are making a risky choice",
    "the children are ignoring the hazards",
    "the children are not paying attention to safety",
    "the children are in a dangerous spot",
    "the children are beside a tipping stool",
    "the children are near the wet floor",
    "the children are creating a mess",
    "the children are sneaking behind the mother",
    "the children are doing something secretly",
    "the children are taking food while mother works",
    "the children are focused on the jar",
    "the children are not focused on the spill",
    "the children are causing trouble",
    "the children are in the left side of the kitchen",
    "the children are under the cabinet",
    "the children are near the counter",
    "the stool is tilted backward",
    "the stool is slipping out from under the boy",
    "the stool is no longer flat on the floor",
    "the stool is balanced on two legs",
    "the stool is falling toward the girl",
    "the stool is falling away from the counter",
    "the stool is unsafe for climbing",
    "the stool is being used like a ladder",
    "the stool cannot support the boy safely",
    "the stool creates a fall risk",
    "the stool may hit the girl",
    "the stool may slide on the floor",
    "the stool is part of the accident",
    "the boy's foot is on the stool",
    "the boy's balance is poor",
    "the boy's body is leaning too far",
    "the boy's arm is stretched too far",
    "the boy's posture looks unstable",
    "the boy could hit the counter",
    "the boy could drop the cookies",
    "the boy could fall onto the floor",
    "the boy could fall into the girl",
    "the boy could be injured",
    "the girl could be hit by the stool",
    "the girl could slip on the water",
    "the wet floor could cause a fall",
    "the water creates a slipping hazard",
    "the overflowing sink creates a mess",
    "the running faucet creates a flood",
    "the faucet continues to run",
    "the faucet has been left unattended",
    "the faucet is filling the sink too much",
    "the sink water has reached the edge",
    "the sink is spilling over the front",
    "the sink is overflowing onto the counter",
    "the water is dripping down the cabinet",
    "the water is running down toward the floor",
    "the water is spreading across the floor",
    "the water is pooling near the woman's shoes",
    "the water is pooling under the sink",
    "the water is spilling beside the mother",
    "the water is falling in a stream",
    "the water is splashing onto the floor",
    "the water is not being cleaned up",
    "the mother may step in the water",
    "the children may slip on the water",
    "the kitchen floor is becoming slippery",
    "the puddle is getting larger",
    "the puddle is under the sink area",
    "the puddle is near the woman's feet",
    "the spill has gone unnoticed",
    "the spill is caused by the faucet",
    "the spill is caused by the full sink",
    "the countertop is wet from overflow",
    "the dishwater is overflowing",
    "the basin is filled past capacity",
    "the drain may be blocked",
    "the faucet should be turned off",
    "the mother should notice the faucet",
    "the mother should notice the spill",
    "the mother should supervise the children",
    "the open cabinet draws attention",
    "the open cabinet reveals the cookie jar",
    "the cabinet is above the children",
    "the cabinet door swings open",
    "the cabinet shelf holds the cookie jar",
    "the cabinet shelf is too high for the children",
    "the cookie jar sits near the shelf edge",
    "the cookie jar is within the boy's reach",
    "the cookie jar is labeled",
    "the cookie jar is being opened",
    "the cookie jar may fall",
    "the cookie jar could break",
    "the cookie jar is the children's target",
    "the cookies are visible in the jar",
    "the cookies are being handed down",
    "the cookies are being shared secretly",
    "the cookies are being taken without asking",
    "the cookies are high above the counter",
    "the cookies attract the children",
    "the cabinet is left open during the theft",
    "the counter below the cabinet is clear enough to climb near",
    "the kitchen shelf holds food",
    "the upper cabinet contains snacks",
    "the boy is reaching into storage",
    "the scene shows a cookie theft",
    "the scene shows poor supervision",
    "the scene shows divided attention",
    "the scene shows two hazards at once",
    "the scene shows a fall hazard and a flood",
    "the scene shows children misbehaving",
    "the scene shows household chaos",
    "the scene shows an ordinary kitchen accident",
    "the scene shows a mother missing danger",
    "the scene shows water damage starting",
    "the scene shows unsafe climbing",
    "the scene shows a possible injury",
    "the scene shows an accident about to happen",
    "the scene shows a messy kitchen moment",
    "the scene shows multitasking gone wrong",
    "the scene shows inattention to the faucet",
    "the scene shows children acting independently",
    "the scene shows a family kitchen problem",
    "the scene shows several simultaneous events",
    "the kitchen has a high cabinet",
    "the kitchen has a long counter",
    "the kitchen has dishes near the sink",
    "the kitchen has a window over the sink",
    "the kitchen has curtains on both sides",
    "the kitchen has a tiled or plain floor",
    "the kitchen has a cabinet under the sink",
    "the kitchen counter is crowded",
    "the sink area is cluttered",
    "the dish towel is in the woman's hand",
    "the plate is being dried",
    "the plate is held upright",
    "the dishes are stacked by the sink",
    "the cup is near the sink",
    "the bowl is near the counter",
    "the water falls beside the cabinets",
    "the window suggests daytime",
    "the curtains hang beside the window",
    "the outside view is visible through the window",
    "the mother is placed on the right",
    "the children are placed on the left",
    "the faucet is near the center-right",
    "the jar is in the upper-left cabinet",
    "the stool is below the boy",
    "the girl is below the boy's arm",
    "the counter separates the children from the sink",
    "the drawing uses simple black outlines",
    "the picture has no color",
    "the image is a classic Cookie Theft scene",
    "the picture is used for speech description",
    "the picture contains action and hazards",
    "the picture asks the viewer to describe events",
    "the picture contains a mother and two children",
    "the picture contains a kitchen sink and cabinet",
    "the picture contains cookies, water, and dishes",
    "the picture includes everyday household objects",
    "the picture includes a safety problem",
    "the picture includes a supervision problem",
    "the mother is not looking at the boy",
    "the mother is not looking at the faucet",
    "the mother is not looking at the puddle",
    "the mother is not looking at the girl",
    "the mother seems unaware of everything happening",
    "the mother might be daydreaming",
    "the mother might be distracted",
    "the mother is calm despite the chaos",
    "the mother is doing dishes while problems unfold",
    "the mother is standing very close to the overflow",
    "the mother may be stepping in water",
    "the mother may slip because of the spill",
    "the mother could turn and see the children",
    "the mother could turn off the faucet",
    "the mother could prevent the fall"
]


print("Number of reference Cookie Theft phrases:", len(cookie_phrases))

def get_texts_for_split(split_name):
    """
    Tries to find transcript/text list inside splits[split_name].
    Works if your notebook stores text as:
        splits[split]["text"]
        splits[split]["texts"]
        splits[split]["transcripts"]
        splits[split]["utt_texts"]

    If this errors, print(splits[split].keys()) and adjust the key.
    """
    s = splits[split_name]

    possible_keys = ["text", "texts", "transcript", "transcripts", "utt_texts"]

    for key in possible_keys:
        if key in s:
            return list(s[key])

    raise ValueError(
        f"Could not find transcript text in splits['{split_name}']. "
        f"Available keys are: {list(s.keys())}. "
        "Change get_texts_for_split() to use the correct text key."
    )


tr_texts = get_texts_for_split("train")
dv_texts = get_texts_for_split("dev")
te_texts = get_texts_for_split("test")

print("Train transcripts:", len(tr_texts))
print("Dev transcripts:", len(dv_texts))
print("Test transcripts:", len(te_texts))

sbert_model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

phrase_emb = sbert_model.encode(
    cookie_phrases,
    convert_to_numpy=True,
    normalize_embeddings=True
)

tr_emb = sbert_model.encode(
    tr_texts,
    convert_to_numpy=True,
    normalize_embeddings=True
)

dv_emb = sbert_model.encode(
    dv_texts,
    convert_to_numpy=True,
    normalize_embeddings=True
)

te_emb = sbert_model.encode(
    te_texts,
    convert_to_numpy=True,
    normalize_embeddings=True
)

print("Phrase embedding shape:", phrase_emb.shape)
print("Train transcript embedding shape:", tr_emb.shape)

def make_cookie_semantic_features(text_emb, phrase_emb):
    """
    Computes similarity between each transcript and each Cookie Theft phrase.

    Features include:
        - similarity to each phrase
        - mean similarity
        - max similarity
        - std similarity
        - top-3 average similarity
        - coverage above thresholds
    """

    # cosine similarity because embeddings are normalized
    sims = text_emb @ phrase_emb.T

    mean_sim = sims.mean(axis=1, keepdims=True)
    max_sim = sims.max(axis=1, keepdims=True)
    min_sim = sims.min(axis=1, keepdims=True)
    std_sim = sims.std(axis=1, keepdims=True)

    sorted_sims = np.sort(sims, axis=1)
    top3_mean = sorted_sims[:, -3:].mean(axis=1, keepdims=True)
    top5_mean = sorted_sims[:, -5:].mean(axis=1, keepdims=True)

    coverage_035 = (sims > 0.35).mean(axis=1, keepdims=True)
    coverage_045 = (sims > 0.45).mean(axis=1, keepdims=True)
    coverage_055 = (sims > 0.55).mean(axis=1, keepdims=True)

    X = np.hstack([
        sims,
        mean_sim,
        max_sim,
        min_sim,
        std_sim,
        top3_mean,
        top5_mean,
        coverage_035,
        coverage_045,
        coverage_055
    ])

    return X, sims


Xtr_sem, tr_phrase_sims = make_cookie_semantic_features(tr_emb, phrase_emb)
Xdv_sem, dv_phrase_sims = make_cookie_semantic_features(dv_emb, phrase_emb)
Xte_sem, te_phrase_sims = make_cookie_semantic_features(te_emb, phrase_emb)

print("Semantic train feature shape:", Xtr_sem.shape)
print("Semantic dev feature shape:", Xdv_sem.shape)
print("Semantic test feature shape:", Xte_sem.shape)

sem_scaler = StandardScaler()

Xtr_sem_s = sem_scaler.fit_transform(Xtr_sem)
Xdv_sem_s = sem_scaler.transform(Xdv_sem)
Xte_sem_s = sem_scaler.transform(Xte_sem)

C_values = [0.01, 0.03, 0.1, 0.3, 1, 3, 10]

sem_rows = []
best_sem_clf = None
best_sem_C = None
best_sem_auc = -1

for C in C_values:
    clf_sem = LogisticRegression(
        C=C,
        max_iter=5000,
        class_weight="balanced"
    )

    clf_sem.fit(Xtr_sem_s, ytr)

    dev_probs = clf_sem.predict_proba(Xdv_sem_s)[:, 1]
    dev_preds = (dev_probs >= 0.5).astype(int)

    acc = accuracy_score(ydv, dev_preds)
    macro_f1 = f1_score(ydv, dev_preds, average="macro")
    auc = roc_auc_score(ydv, dev_probs)

    sem_rows.append({
        "C": C,
        "dev_accuracy": acc,
        "dev_macro_f1": macro_f1,
        "dev_auroc": auc
    })

    if auc > best_sem_auc:
        best_sem_auc = auc
        best_sem_C = C
        best_sem_clf = clf_sem

sem_dev_results = pd.DataFrame(sem_rows)

print("Best semantic phrase model:")
print("Best C:", best_sem_C)
print("Best dev AUROC:", best_sem_auc)

display(sem_dev_results.sort_values("dev_auroc", ascending=False))

sem_dev_seg_probs = best_sem_clf.predict_proba(Xdv_sem_s)[:, 1]
sem_test_seg_probs = best_sem_clf.predict_proba(Xte_sem_s)[:, 1]

sem_dev_probs, sem_dev_y, sem_dev_sessions = aggregate_sessions(
    dv_u,
    sem_dev_seg_probs,
    ydv,
    sr_dv
)

sem_test_probs, sem_test_y, sem_test_sessions = aggregate_sessions(
    te_u,
    sem_test_seg_probs,
    yte,
    sr_te
)

semantic_dev_df = pd.DataFrame({
    "model": "Cookie semantic phrase model",
    "session": sem_dev_sessions,
    "y_true": sem_dev_y,
    "prob_AD": sem_dev_probs
})

semantic_dev_df["y_pred"] = (semantic_dev_df["prob_AD"] >= 0.5).astype(int)

semantic_test_df = pd.DataFrame({
    "model": "Cookie semantic phrase model",
    "session": sem_test_sessions,
    "y_true": sem_test_y,
    "prob_AD": sem_test_probs
})

semantic_test_df["y_pred"] = (semantic_test_df["prob_AD"] >= 0.5).astype(int)

display(semantic_dev_df.head())
display(semantic_test_df.head())

def session_probs_to_df(model_name, session_output):
    """
    Converts get_session_probs output into a DataFrame.
    Automatically detects:
        - session IDs: strings like '022-2'
        - labels: 0/1 integers
        - probabilities: floats between 0 and 1
    """

    if not isinstance(session_output, (tuple, list)):
        raise ValueError(f"Expected tuple/list, got {type(session_output)}")

    if len(session_output) != 3:
        raise ValueError(f"Expected 3 outputs, got {len(session_output)}")

    parts = []

    for item in session_output:
        arr = np.asarray(item).ravel()
        parts.append(arr)

    session_ids = None
    session_y = None
    session_probs = None

    for arr in parts:
        numeric_arr = pd.to_numeric(pd.Series(arr), errors="coerce").values

        if np.isnan(numeric_arr).all():
            session_ids = arr.astype(str)


        elif set(np.unique(numeric_arr)).issubset({0, 1}):
            session_y = numeric_arr.astype(int)


        elif np.all((numeric_arr >= 0) & (numeric_arr <= 1)):
            session_probs = numeric_arr.astype(float)

    if session_ids is None:
        raise ValueError("Could not detect session IDs.")

    if session_y is None:
        raise ValueError("Could not detect true labels.")

    if session_probs is None:
        raise ValueError("Could not detect probabilities.")

    df = pd.DataFrame({
        "model": [model_name] * len(session_ids),
        "session": session_ids,
        "y_true": session_y,
        "prob_AD": session_probs
    })

    df["y_pred"] = (df["prob_AD"] >= 0.5).astype(int)

    return df

text_dev_df = text_dev_df.sort_values("session").reset_index(drop=True)
semantic_dev_df = semantic_dev_df.sort_values("session").reset_index(drop=True)

text_test_df = text_test_df.sort_values("session").reset_index(drop=True)
semantic_test_df = semantic_test_df.sort_values("session").reset_index(drop=True)

assert np.all(text_dev_df["session"].values == semantic_dev_df["session"].values)
assert np.all(text_test_df["session"].values == semantic_test_df["session"].values)

assert np.all(text_dev_df["y_true"].values == semantic_dev_df["y_true"].values)
assert np.all(text_test_df["y_true"].values == semantic_test_df["y_true"].values)

print("Text and semantic models are aligned.")

w_text = 0.5
w_semantic = 0.5
threshold = 0.5

dev_y = text_dev_df["y_true"].values
test_y = text_test_df["y_true"].values

text_dev_probs = text_dev_df["prob_AD"].values
sem_dev_probs = semantic_dev_df["prob_AD"].values

text_test_probs = text_test_df["prob_AD"].values
sem_test_probs = semantic_test_df["prob_AD"].values

dev_fused_probs = (
    w_text * text_dev_probs
    + w_semantic * sem_dev_probs
)

test_fused_probs = (
    w_text * text_test_probs
    + w_semantic * sem_test_probs
)

dev_fused_preds = (dev_fused_probs >= threshold).astype(int)
test_fused_preds = (test_fused_probs >= threshold).astype(int)

fusion_dev_df = pd.DataFrame({
    "model": f"Fixed fusion text={w_text:.2f}, semantic={w_semantic:.2f}, threshold={threshold:.2f}",
    "session": text_dev_df["session"].values,
    "y_true": dev_y,
    "prob_AD": dev_fused_probs,
    "y_pred": dev_fused_preds
})

fusion_test_df = pd.DataFrame({
    "model": f"Fixed fusion text={w_text:.2f}, semantic={w_semantic:.2f}, threshold={threshold:.2f}",
    "session": text_test_df["session"].values,
    "y_true": test_y,
    "prob_AD": test_fused_probs,
    "y_pred": test_fused_preds
})

display(fusion_dev_df.head())
display(fusion_test_df.head())




def metrics_for_group(df):
    y_true = df["y_true"].values
    y_pred = df["y_pred"].values
    y_prob = df["prob_AD"].values

    out = {
        "n_sessions": len(df),
        "n_control": int(np.sum(y_true == 0)),
        "n_AD": int(np.sum(y_true == 1)),
        "accuracy": accuracy_score(y_true, y_pred),
        "macro_f1": f1_score(y_true, y_pred, average="macro"),
        "confusion": confusion_matrix(y_true, y_pred).tolist()
    }

    if len(np.unique(y_true)) == 2:
        out["auroc"] = roc_auc_score(y_true, y_prob)
    else:
        out["auroc"] = np.nan

    return out




fusion_dev_overall = metrics_for_group(fusion_dev_df)
fusion_test_overall = metrics_for_group(fusion_test_df)

fusion_overall_df = pd.DataFrame([
    {
        "split": "dev",
        "model": fusion_dev_df["model"].iloc[0],
        "n_sessions": fusion_dev_overall["n_sessions"],
        "n_control": fusion_dev_overall["n_control"],
        "n_AD": fusion_dev_overall["n_AD"],
        "accuracy": fusion_dev_overall["accuracy"],
        "macro_f1": fusion_dev_overall["macro_f1"],
        "auroc": fusion_dev_overall["auroc"],
        "confusion": fusion_dev_overall["confusion"]
    },
    {
        "split": "test",
        "model": fusion_test_df["model"].iloc[0],
        "n_sessions": fusion_test_overall["n_sessions"],
        "n_control": fusion_test_overall["n_control"],
        "n_AD": fusion_test_overall["n_AD"],
        "accuracy": fusion_test_overall["accuracy"],
        "macro_f1": fusion_test_overall["macro_f1"],
        "auroc": fusion_test_overall["auroc"],
        "confusion": fusion_test_overall["confusion"]
    }
])

print("Fixed text + semantic fusion performance:")
display(fusion_overall_df)



print("Dev confusion matrix:")
print(confusion_matrix(fusion_dev_df["y_true"], fusion_dev_df["y_pred"]))

print("Test confusion matrix:")
print(confusion_matrix(fusion_test_df["y_true"], fusion_test_df["y_pred"]))



metrics = ["accuracy", "macro_f1", "auroc"]

for metric in metrics:
    plt.figure(figsize=(6, 4))
    plt.bar(fusion_overall_df["split"], fusion_overall_df[metric])
    plt.title(f"Fixed Text + Semantic Fusion {metric}")
    plt.xlabel("Split")
    plt.ylabel(metric)
    plt.ylim(0, 1)
    plt.grid(axis="y")
    plt.show()




cm = confusion_matrix(fusion_test_df["y_true"], fusion_test_df["y_pred"])

plt.figure(figsize=(5, 4))
plt.imshow(cm)
plt.title("Test Confusion Matrix: Text + Semantic Fusion")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.xticks([0, 1], ["Control", "AD"])
plt.yticks([0, 1], ["Control", "AD"])

for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        plt.text(j, i, cm[i, j], ha="center", va="center")

plt.colorbar()
plt.show()